export default [
  { id: 0, name: 'Bare Handed', lefthand: true },
  { id: 1, name: 'Dagger', lefthand: true },
  { id: 2, name: '1H Sword', lefthand: true },
  { id: 3, name: '2H Sword', lefthand: false },
  { id: 4, name: '1H Spear', lefthand: true },
  { id: 5, name: '2H Spear', lefthand: false },
  { id: 6, name: '1H Axe', lefthand: true },
  { id: 7, name: '2H Axe', lefthand: false },
  { id: 8, name: 'Mace', lefthand: true },
  { id: 9, name: '1H Staff', lefthand: true },
  { id: 10, name: 'Bow', lefthand: false },
  { id: 11, name: 'Katar', lefthand: false },
  { id: 12, name: 'Book', lefthand: true },
  { id: 13, name: 'Fist', lefthand: true },
  { id: 14, name: 'Instrument/Whip', lefthand: false },
  { id: 15, name: '2H Staff', lefthand: true },
  { id: 16, name: 'Huuma Shuriken', lefthand: false },
  { id: 17, name: '!handgun!', lefthand: false },
  { id: 18, name: '!rifle!', lefthand: false },
  { id: 19, name: '!shotgun!', lefthand: false },
  { id: 20, name: '!Machine Gun!', lefthand: false },
  { id: 21, name: '!Grenade Launcher!', lefthand: false },
];
